# Generated by Django 2.2.4 on 2020-04-23 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200423_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='unit_no',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
