# Generated by Django 2.2.4 on 2020-05-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200504_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='gift',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(blank=True, default='Canada', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
