# Generated by Django 2.2.4 on 2020-04-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20200423_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='banner',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='best_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='hot_item',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='on_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='top_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
