# Generated by Django 2.2.4 on 2020-04-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20200423_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='banner1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='banner2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='banner3',
            field=models.BooleanField(default=False),
        ),
    ]
