# Generated by Django 2.2.4 on 2020-04-23 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20200423_2212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-updated_at', 'name')},
        ),
        migrations.RemoveField(
            model_name='product',
            name='best_seller',
        ),
        migrations.RemoveField(
            model_name='product',
            name='top_viewed',
        ),
        migrations.RemoveField(
            model_name='product',
            name='trending',
        ),
    ]
