# Generated by Django 2.2.4 on 2020-04-23 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20200424_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fast_available',
            field=models.BooleanField(default=False),
        ),
    ]
